server:
  port: 8080

spring:
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local

  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
    redis:
      repositories:
        enabled: true
    elasticsearch:
      repositories:
        enabled: true

  datasource:
    username: agramar
    password: agramar0!
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/agramar
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: HIKARI-POOL

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true

  redis:
    host: localhost
    port: 6379
    password: changeme
    lettuce:
      pool:
        max-active: 4
        max-idle: 4
        min-idle: 2

  elasticsearch:
    rest:
      uris: localhost:9200
      username:
      password:
      connection-timeout: 5s
      read-timeout: 30s

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      max-poll-records: 500
      group-id: demo-group
    listener:
      concurrency: 10
      poll-timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: kr.co.agramar.demo.*.model.vo
  configuration:
    mapUnderscoreToCamelCase: true
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    callSettersOnNulls: true
    jdbcTypeForNull: VARCHAR
    returnInstanceForEmptyRow: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ '*' ]

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
    use-default-objectmapper: true
  servlet:
    mapping: /graphql
    max-query-depth: 100
    tracing-enabled: false
    exception-handlers-enabled: true
    subscriptions:
      apollo:
        keep-alive-enabled: false
  playground:
    enabled: true

voyager:
  enabled: true

logging:
  logstash:
    host: localhost
    port: 5000

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stag

---
spring:
  config:
    activate:
      on-profile: prod
