version: "3.2"

services:
  mariadb:
    build:
      context: mariadb/
      args:
        MARIADB_VERSION: $MARIADB_VERSION
    container_name: mariadb-$MARIADB_VERSION
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root0!
      MYSQL_DATABASE: agramar
      MYSQL_USER: agramar
      MYSQL_PASSWORD: agramar0!
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

  redis:
    build:
      context: redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log
      - ./redis/data:/usr/local/redis/data
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
