server:
  port: 8080

spring:
  application:
    name: api
  profiles:
    active: local
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ 'refresh' ]

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: agramar
    password: agramar0!
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/agramar
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: HIKARI-POOL

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://localhost

---
spring:
  config:
    activate:
      on-profile: stag
  cloud:
    config:
      uri: http://localhost
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: http://localhost
